// Mapeamento de cidades e unidades para prazos de entrega (em dias)
export const prazosEntrega = [
  { cidade: 'BALNEARIO CAMBORIU', unidade: 'BLU', prazo: 1 },
  { cidade: 'BALNEARIO PICARRAS', unidade: 'BLU', prazo: 2 },
  { cidade: 'BOMBINHAS', unidade: 'BLU', prazo: 2 },
  { cidade: 'BOTUVERA', unidade: 'BLU', prazo: 4 },
  { cidade: 'BRUSQUE', unidade: 'BLU', prazo: 2 },
  { cidade: 'CAMBORIU', unidade: 'BLU', prazo: 1 },
  { cidade: 'GUABIRUBA', unidade: 'BLU', prazo: 5 },
  { cidade: 'ITAJAI', unidade: 'BLU', prazo: 1 },
  { cidade: 'ITAPEMA', unidade: 'BLU', prazo: 2 },
  { cidade: 'LUIZ ALVES', unidade: 'BLU', prazo: 4 },
  { cidade: 'NAVEGANTES', unidade: 'BLU', prazo: 2 },
  { cidade: 'PENHA', unidade: 'BLU', prazo: 2 },
  { cidade: 'PORTO BELO', unidade: 'BLU', prazo: 2 },
  { cidade: 'BENEDITO NOVO', unidade: 'BNU', prazo: 3 },
  { cidade: 'BLUMENAU', unidade: 'BNU', prazo: 1 },
  { cidade: 'DOUTOR PEDRINHO', unidade: 'BNU', prazo: 3 },
  { cidade: 'GASPAR', unidade: 'BNU', prazo: 3 },
  { cidade: 'ILHOTA', unidade: 'BNU', prazo: 4 },
  { cidade: 'INDAIAL', unidade: 'BNU', prazo: 3 },
  { cidade: 'POMERODE', unidade: 'BNU', prazo: 2 },
  { cidade: 'RIO DOS CEDROS', unidade: 'BNU', prazo: 3 },
  { cidade: 'TIMBO', unidade: 'BNU', prazo: 3 },
  { cidade: 'AGUAS MORNAS', unidade: 'PLC', prazo: 3 },
  { cidade: 'ANGELINA', unidade: 'PLC', prazo: 3 },
  { cidade: 'ANITAPOLIS', unidade: 'PLC', prazo: 3 },
  { cidade: 'ANTONIO CARLOS', unidade: 'PLC', prazo: 3 },
  { cidade: 'CANELINHA', unidade: 'PLC', prazo: 3 },
  { cidade: 'GOVERNADOR CELSO RAMOS', unidade: 'PLC', prazo: 3 },
  { cidade: 'MAJOR GERCINO', unidade: 'PLC', prazo: 4 },
  { cidade: 'NOVA TRENTO', unidade: 'PLC', prazo: 3 },
  { cidade: 'RANCHO QUEIMADO', unidade: 'PLC', prazo: 3 },
  { cidade: 'SANTO AMARO DA IMPERATRIZ', unidade: 'PLC', prazo: 3 },
  { cidade: 'SAO BONIFACIO', unidade: 'PLC', prazo: 3 },
  { cidade: 'SAO JOAO BATISTA', unidade: 'PLC', prazo: 3 },
  { cidade: 'SAO PEDRO DE ALCANTARA', unidade: 'PLC', prazo: 3 },
  { cidade: 'TIJUCAS', unidade: 'PLC', prazo: 3 },
  { cidade: 'AGROLANDIA', unidade: 'RDS', prazo: 2 },
  { cidade: 'AGRONOMICA', unidade: 'RDS', prazo: 2 },
  { cidade: 'APIUNA', unidade: 'RDS', prazo: 2 },
  { cidade: 'ASCURRA', unidade: 'RDS', prazo: 2 },
  { cidade: 'ATALANTA', unidade: 'RDS', prazo: 2 },
  { cidade: 'AURORA', unidade: 'RDS', prazo: 2 },
  { cidade: 'BRACO DO TROMBUDO', unidade: 'RDS', prazo: 2 },
  { cidade: 'CHAPADAO DO LAGEADO', unidade: 'RDS', prazo: 2 },
  { cidade: 'DONA EMMA', unidade: 'RDS', prazo: 2 },
  { cidade: 'IBIRAMA', unidade: 'RDS', prazo: 2 },
  { cidade: 'IMBUIA', unidade: 'RDS', prazo: 2 },
  { cidade: 'ITUPORANGA', unidade: 'RDS', prazo: 2 },
  { cidade: 'JOSE BOITEUX', unidade: 'RDS', prazo: 2 },
  { cidade: 'LAURENTINO', unidade: 'RDS', prazo: 2 },
  { cidade: 'LEOBERTO LEAL', unidade: 'RDS', prazo: 2 },
  { cidade: 'LONTRAS', unidade: 'RDS', prazo: 2 },
  { cidade: 'MIRIM DOCE', unidade: 'RDS', prazo: 2 },
  { cidade: 'PETROLANDIA', unidade: 'RDS', prazo: 2 },
  { cidade: 'POUSO REDONDO', unidade: 'RDS', prazo: 2 },
  { cidade: 'PRESIDENTE GETULIO', unidade: 'RDS', prazo: 2 },
  { cidade: 'PRESIDENTE NEREU', unidade: 'RDS', prazo: 2 },
  { cidade: 'RIO DO CAMPO', unidade: 'RDS', prazo: 2 },
  { cidade: 'RIO DO OESTE', unidade: 'RDS', prazo: 2 },
  { cidade: 'RIO DO SUL', unidade: 'RDS', prazo: 1 },
  { cidade: 'RODEIO', unidade: 'RDS', prazo: 2 },
  { cidade: 'SALETE', unidade: 'RDS', prazo: 2 },
  { cidade: 'SANTA TEREZINHA', unidade: 'RDS', prazo: 2 },
  { cidade: 'TAIO', unidade: 'RDS', prazo: 2 },
  { cidade: 'TROMBUDO CENTRAL', unidade: 'RDS', prazo: 2 },
  { cidade: 'VIDAL RAMOS', unidade: 'RDS', prazo: 2 },
  { cidade: 'VITOR MEIRELES', unidade: 'RDS', prazo: 2 },
  { cidade: 'WITMARSUM', unidade: 'RDS', prazo: 2 },
  { cidade: 'ALFREDO WAGNER', unidade: 'LGE', prazo: 3 },
  { cidade: 'ANITA GARIBALDI', unidade: 'LGE', prazo: 3 },
  { cidade: 'BOCAINA DO SUL', unidade: 'LGE', prazo: 3 },
  { cidade: 'BOM JARDIM DA SERRA', unidade: 'LGE', prazo: 3 },
  { cidade: 'BOM RETIRO', unidade: 'LGE', prazo: 3 },
  { cidade: 'CAMPO BELO DO SUL', unidade: 'LGE', prazo: 3 },
  { cidade: 'CAPAO ALTO', unidade: 'LGE', prazo: 3 },
  { cidade: 'CELSO RAMOS', unidade: 'LGE', prazo: 3 },
  { cidade: 'CERRO NEGRO', unidade: 'LGE', prazo: 4 },
  { cidade: 'CORREIA PINTO', unidade: 'LGE', prazo: 2 },
  { cidade: 'CURITIBANOS', unidade: 'LGE', prazo: 2 },
  { cidade: 'FREI ROGERIO', unidade: 'LGE', prazo: 3 },
  { cidade: 'LAGES', unidade: 'LGE', prazo: 1 },
  { cidade: 'LEBON REGIS', unidade: 'LGE', prazo: 4 },
  { cidade: 'OTACILIO COSTA', unidade: 'LGE', prazo: 2 },
  { cidade: 'PAINEL', unidade: 'LGE', prazo: 3 },
  { cidade: 'PALMEIRA', unidade: 'LGE', prazo: 3 },
  { cidade: 'PONTE ALTA', unidade: 'LGE', prazo: 2 },
  { cidade: 'PONTE ALTA DO NORTE', unidade: 'LGE', prazo: 4 },
  { cidade: 'RIO RUFINO', unidade: 'LGE', prazo: 3 },
  { cidade: 'SANTA CECILIA', unidade: 'LGE', prazo: 3 },
  { cidade: 'SAO CRISTOVAO DO SUL', unidade: 'LGE', prazo: 3 },
  { cidade: 'SAO JOAQUIM', unidade: 'LGE', prazo: 2 },
  { cidade: 'SAO JOSE DO CERRITO', unidade: 'LGE', prazo: 3 },
  { cidade: 'URUBICI', unidade: 'LGE', prazo: 2 },
  { cidade: 'URUPEMA', unidade: 'LGE', prazo: 3 },
  { cidade: 'ARMAZEM', unidade: 'TBR', prazo: 3 },
  { cidade: 'BRACO DO NORTE', unidade: 'TBR', prazo: 3 },
  { cidade: 'CAPIVARI DE BAIXO', unidade: 'TBR', prazo: 2 },
  { cidade: 'GAROPABA', unidade: 'TBR', prazo: 3 },
  { cidade: 'GRAO PARA', unidade: 'TBR', prazo: 3 },
  { cidade: 'GRAVATAL', unidade: 'TBR', prazo: 3 },
  { cidade: 'IMARUI', unidade: 'TBR', prazo: 3 },
  { cidade: 'IMBITUBA', unidade: 'TBR', prazo: 3 },
  { cidade: 'JAGUARUNA', unidade: 'TBR', prazo: 4 },
  { cidade: 'LAGUNA', unidade: 'TBR', prazo: 3 },
  { cidade: 'LAURO MULLER', unidade: 'TBR', prazo: 3 },
  { cidade: 'ORLEANS', unidade: 'TBR', prazo: 3 },
  { cidade: 'PAULO LOPES', unidade: 'TBR', prazo: 3 },
  { cidade: 'PEDRAS GRANDES', unidade: 'TBR', prazo: 3 },
  { cidade: 'PESCARIA BRAVA', unidade: 'TBR', prazo: 3 },
  { cidade: 'RIO FORTUNA', unidade: 'TBR', prazo: 3 },
  { cidade: 'SANGAO', unidade: 'TBR', prazo: 3 },
  { cidade: 'SANTA ROSA DE LIMA', unidade: 'TBR', prazo: 3 },
  { cidade: 'SAO LUDGERO', unidade: 'TBR', prazo: 3 },
  { cidade: 'SAO MARTINHO', unidade: 'TBR', prazo: 4 },
  { cidade: 'TREZE DE MAIO', unidade: 'TBR', prazo: 3 },
  { cidade: 'TUBARAO', unidade: 'TBR', prazo: 1 },
  { cidade: 'ABDON BATISTA', unidade: 'JCA', prazo: 4 },
  { cidade: 'AGUA DOCE', unidade: 'JCA', prazo: 3 },
  { cidade: 'ALTO BELA VISTA', unidade: 'JCA', prazo: 3 },
  { cidade: 'ARABUTA', unidade: 'JCA', prazo: 3 },
  { cidade: 'ARROIO TRINTA', unidade: 'JCA', prazo: 3 },
  { cidade: 'BRUNOPOLIS', unidade: 'JCA', prazo: 5 },
  { cidade: 'CACADOR', unidade: 'JCA', prazo: 2 },
  { cidade: 'CALMON', unidade: 'JCA', prazo: 3 },
  { cidade: 'CAMPOS NOVOS', unidade: 'JCA', prazo: 2 },
  { cidade: 'CAPINZAL', unidade: 'JCA', prazo: 2 },
  { cidade: 'CATANDUVAS', unidade: 'JCA', prazo: 3 },
  { cidade: 'CONCORDIA', unidade: 'JCA', prazo: 2 },
  { cidade: 'ERVAL VELHO', unidade: 'JCA', prazo: 3 },
  { cidade: 'FAXINAL DOS GUEDES', unidade: 'JCA', prazo: 3 },
  { cidade: 'FRAIBURGO', unidade: 'JCA', prazo: 3 },
  { cidade: 'HERVAL D OESTE', unidade: 'JCA', prazo: 2 },
  { cidade: 'IBIAM', unidade: 'JCA', prazo: 4 },
  { cidade: 'IBICARE', unidade: 'JCA', prazo: 3 },
  { cidade: 'IOMERE', unidade: 'JCA', prazo: 3 },
  { cidade: 'IPIRA', unidade: 'JCA', prazo: 3 },
  { cidade: 'IPUMIRIM', unidade: 'JCA', prazo: 3 },
  { cidade: 'IRANI', unidade: 'JCA', prazo: 2 },
  { cidade: 'ITA', unidade: 'JCA', prazo: 3 },
  { cidade: 'JABORA', unidade: 'JCA', prazo: 2 },
  { cidade: 'JOACABA', unidade: 'JCA', prazo: 1 },
  { cidade: 'LACERDOPOLIS', unidade: 'JCA', prazo: 3 },
  { cidade: 'LINDOIA DO SUL', unidade: 'JCA', prazo: 3 },
  { cidade: 'LUZERNA', unidade: 'JCA', prazo: 2 },
  { cidade: 'MACIEIRA', unidade: 'JCA', prazo: 3 },
  { cidade: 'MATOS COSTA', unidade: 'JCA', prazo: 3 },
  { cidade: 'MONTE CARLO', unidade: 'JCA', prazo: 3 },
  { cidade: 'OURO', unidade: 'JCA', prazo: 3 },
  { cidade: 'PASSOS MAIA', unidade: 'JCA', prazo: 3 },
  { cidade: 'PERITIBA', unidade: 'JCA', prazo: 3 },
  { cidade: 'PINHEIRO PRETO', unidade: 'JCA', prazo: 2 },
  { cidade: 'PIRATUBA', unidade: 'JCA', prazo: 3 },
  { cidade: 'PONTE SERRADA', unidade: 'JCA', prazo: 3 },
  { cidade: 'PRESIDENTE CASTELLO BRANCO', unidade: 'JCA', prazo: 3 },
  { cidade: 'RIO DAS ANTAS', unidade: 'JCA', prazo: 3 },
  { cidade: 'SALTO VELOSO', unidade: 'JCA', prazo: 2 },
  { cidade: 'SEARA', unidade: 'JCA', prazo: 2 },
  { cidade: 'TANGARA', unidade: 'JCA', prazo: 3 },
  { cidade: 'TIMBO GRANDE', unidade: 'JCA', prazo: 3 },
  { cidade: 'TREZE TILIAS', unidade: 'JCA', prazo: 3 },
  { cidade: 'VARGEAO', unidade: 'JCA', prazo: 4 },
  { cidade: 'VARGEM', unidade: 'JCA', prazo: 3 },
  { cidade: 'VARGEM BONITA', unidade: 'JCA', prazo: 3 },
  { cidade: 'VIDEIRA', unidade: 'JCA', prazo: 2 },
  { cidade: 'XAVANTINA', unidade: 'JCA', prazo: 3 },
  { cidade: 'ZORTEA', unidade: 'JCA', prazo: 4 },
  { cidade: 'ARARANGUA', unidade: 'CCA', prazo: 2 },
  { cidade: 'BALNEARIO ARROIO DO SILVA', unidade: 'CCA', prazo: 2 },
  { cidade: 'BALNEARIO GAIVOTA', unidade: 'CCA', prazo: 3 },
  { cidade: 'BALNEARIO RINCAO', unidade: 'CCA', prazo: 3 },
  { cidade: 'COCAL DO SUL', unidade: 'CCA', prazo: 3 },
  { cidade: 'CRICIUMA', unidade: 'CCA', prazo: 1 },
  { cidade: 'ERMO', unidade: 'CCA', prazo: 3 },
  { cidade: 'FORQUILHINHA', unidade: 'CCA', prazo: 2 },
  { cidade: 'ICARA', unidade: 'CCA', prazo: 2 },
  { cidade: 'JACINTO MACHADO', unidade: 'CCA', prazo: 3 },
  { cidade: 'MARACAJA', unidade: 'CCA', prazo: 3 },
  { cidade: 'MELEIRO', unidade: 'CCA', prazo: 4 },
  { cidade: 'MORRO DA FUMACA', unidade: 'CCA', prazo: 2 },
  { cidade: 'MORRO GRANDE', unidade: 'CCA', prazo: 4 },
  { cidade: 'NOVA VENEZA', unidade: 'CCA', prazo: 2 },
  { cidade: 'PASSO DE TORRES', unidade: 'CCA', prazo: 3 },
  { cidade: 'PRAIA GRANDE', unidade: 'CCA', prazo: 3 },
  { cidade: 'SANTA ROSA DO SUL', unidade: 'CCA', prazo: 3 },
  { cidade: 'SAO JOAO DO SUL', unidade: 'CCA', prazo: 3 },
  { cidade: 'SIDEROPOLIS', unidade: 'CCA', prazo: 3 },
  { cidade: 'SOMBRIO', unidade: 'CCA', prazo: 2 },
  { cidade: 'TIMBE DO SUL', unidade: 'CCA', prazo: 3 },
  { cidade: 'TREVISO', unidade: 'CCA', prazo: 3 },
  { cidade: 'TURVO', unidade: 'CCA', prazo: 2 },
  { cidade: 'URUSSANGA', unidade: 'CCA', prazo: 3 },
  { cidade: 'ABELARDO LUZ', unidade: 'CHA', prazo: 3 },
  { cidade: 'AGUAS DE CHAPECO', unidade: 'CHA', prazo: 2 },
  { cidade: 'AGUAS FRIAS', unidade: 'CHA', prazo: 3 },
  { cidade: 'ANCHIETA', unidade: 'CHA', prazo: 2 },
  { cidade: 'ARVOREDO', unidade: 'CHA', prazo: 4 },
  { cidade: 'BANDEIRANTE', unidade: 'CHA', prazo: 3 },
  { cidade: 'BARRA BONITA', unidade: 'CHA', prazo: 3 },
  { cidade: 'BELMONTE', unidade: 'CHA', prazo: 3 },
  { cidade: 'BOM JESUS', unidade: 'CHA', prazo: 3 },
  { cidade: 'BOM JESUS DO OESTE', unidade: 'CHA', prazo: 2 },
  { cidade: 'CAIBI', unidade: 'CHA', prazo: 2 },
  { cidade: 'CAMPO ERE', unidade: 'CHA', prazo: 2 },
  { cidade: 'CAXAMBU DO SUL', unidade: 'CHA', prazo: 2 },
  { cidade: 'CHAPECO', unidade: 'CHA', prazo: 1 },
  { cidade: 'CORDILHEIRA ALTA', unidade: 'CHA', prazo: 3 },
  { cidade: 'CORONEL FREITAS', unidade: 'CHA', prazo: 2 },
  { cidade: 'CORONEL MARTINS', unidade: 'CHA', prazo: 3 },
  { cidade: 'CUNHA PORA', unidade: 'CHA', prazo: 3 },
  { cidade: 'CUNHATAI', unidade: 'CHA', prazo: 3 },
  { cidade: 'DESCANSO', unidade: 'CHA', prazo: 2 },
  { cidade: 'DIONISIO CERQUEIRA', unidade: 'CHA', prazo: 2 },
  { cidade: 'ENTRE RIOS', unidade: 'CHA', prazo: 5 },
  { cidade: 'FLOR DO SERTAO', unidade: 'CHA', prazo: 3 },
  { cidade: 'FORMOSA DO SUL', unidade: 'CHA', prazo: 2 },
  { cidade: 'GALVAO', unidade: 'CHA', prazo: 2 },
  { cidade: 'GUARACIABA', unidade: 'CHA', prazo: 2 },
  { cidade: 'GUARUJA DO SUL', unidade: 'CHA', prazo: 2 },
  { cidade: 'GUATAMBU', unidade: 'CHA', prazo: 3 },
  { cidade: 'IPORA DO OESTE', unidade: 'CHA', prazo: 2 },
  { cidade: 'IPUACU', unidade: 'CHA', prazo: 3 },
  { cidade: 'IRACEMINHA', unidade: 'CHA', prazo: 3 },
  { cidade: 'IRATI', unidade: 'CHA', prazo: 4 },
  { cidade: 'ITAPIRANGA', unidade: 'CHA', prazo: 2 },
  { cidade: 'JARDINOPOLIS', unidade: 'CHA', prazo: 3 },
  { cidade: 'JUPIA', unidade: 'CHA', prazo: 3 },
  { cidade: 'LAJEADO GRANDE', unidade: 'CHA', prazo: 4 },
  { cidade: 'MARAVILHA', unidade: 'CHA', prazo: 2 },
  { cidade: 'MAREMA', unidade: 'CHA', prazo: 3 },
  { cidade: 'MODELO', unidade: 'CHA', prazo: 2 },
  { cidade: 'MONDAI', unidade: 'CHA', prazo: 2 },
  { cidade: 'NOVA ERECHIM', unidade: 'CHA', prazo: 2 },
  { cidade: 'NOVA ITABERABA', unidade: 'CHA', prazo: 4 },
  { cidade: 'NOVO HORIZONTE', unidade: 'CHA', prazo: 2 },
  { cidade: 'OURO VERDE', unidade: 'CHA', prazo: 3 },
  { cidade: 'PAIAL', unidade: 'CHA', prazo: 3 },
  { cidade: 'PALMA SOLA', unidade: 'CHA', prazo: 2 },
  { cidade: 'PALMITOS', unidade: 'CHA', prazo: 2 },
  { cidade: 'PARAISO', unidade: 'CHA', prazo: 3 },
  { cidade: 'PINHALZINHO', unidade: 'CHA', prazo: 2 },
  { cidade: 'PLANALTO ALEGRE', unidade: 'CHA', prazo: 2 },
  { cidade: 'PRINCESA', unidade: 'CHA', prazo: 3 },
  { cidade: 'QUILOMBO', unidade: 'CHA', prazo: 2 },
  { cidade: 'RIQUEZA', unidade: 'CHA', prazo: 2 },
  { cidade: 'ROMELANDIA', unidade: 'CHA', prazo: 3 },
  { cidade: 'SALTINHO', unidade: 'CHA', prazo: 2 },
  { cidade: 'SANTA HELENA', unidade: 'CHA', prazo: 3 },
  { cidade: 'SANTA TEREZINHA DO PROGRESSO', unidade: 'CHA', prazo: 3 },
  { cidade: 'SANTIAGO DO SUL', unidade: 'CHA', prazo: 4 },
  { cidade: 'SAO BERNARDINO', unidade: 'CHA', prazo: 3 },
  { cidade: 'SAO CARLOS', unidade: 'CHA', prazo: 2 },
  { cidade: 'SAO DOMINGOS', unidade: 'CHA', prazo: 2 },
  { cidade: 'SAO JOAO DO OESTE', unidade: 'CHA', prazo: 2 },
  { cidade: 'SAO JOSE DO CEDRO', unidade: 'CHA', prazo: 2 },
  { cidade: 'SAO LOURENCO DO OESTE', unidade: 'CHA', prazo: 2 },
  { cidade: 'SAO MIGUEL DA BOA VISTA', unidade: 'CHA', prazo: 3 },
  { cidade: 'SAO MIGUEL DO OESTE', unidade: 'CHA', prazo: 2 },
  { cidade: 'SAUDADES', unidade: 'CHA', prazo: 3 },
  { cidade: 'SERRA ALTA', unidade: 'CHA', prazo: 2 },
  { cidade: 'SUL BRASIL', unidade: 'CHA', prazo: 3 },
  { cidade: 'TIGRINHOS', unidade: 'CHA', prazo: 3 },
  { cidade: 'TUNAPOLIS', unidade: 'CHA', prazo: 3 },
  { cidade: 'UNIAO DO OESTE', unidade: 'CHA', prazo: 3 },
  { cidade: 'XANXERE', unidade: 'CHA', prazo: 2 },
  { cidade: 'XAXIM', unidade: 'CHA', prazo: 2 }
];

// Função para buscar o prazo de entrega por cidade e unidade
export const getPrazoByCidade = (cidade: string, unidade: string): number | null => {
  const cidadeUpper = cidade.toUpperCase().trim();
  const unidadeUpper = unidade.toUpperCase().trim();
  
  const entrada = prazosEntrega.find(
    item => item.cidade === cidadeUpper && item.unidade === unidadeUpper
  );
  
  return entrada ? entrada.prazo : null;
};